"""Converged finite-volume access resistance of an insulated microwire tip (ledger 129).

Generated by ``scripts/fd_microwire_reference.py``, which imports no part of ``neurostim``:
axisymmetric finite volume outside a semi-infinite insulating rod of radius ``a``, with the
flat end face and ``l`` of shaft held at ``V = 1``, extrapolated in far-box size and then
by Richardson over three refinements. Values are ``R sigma a``, so they are independent of
the wire's size and of the conductivity.

At ``l = 0`` the tip edge is a 270 degree re-entrant corner. Convergence there is slow
(observed order about 0.7), so the value is uncertain by about 2 %: a fourth refinement
moves it to about 0.1729, and the Phase 3 reviewer's independent solve gives 0.1755. The
other entries converge with order 1.2-1.75.

The package's equal-area sphere against this table: -7.8 % at ``l = 0``, within +-1.4 %
from ``0.25a`` to ``5a`` (-1.3 % at ``2a``), +6.7 % at ``10a`` and +17 % at ``20a``. The
package therefore uses Newman's half-space disc, 0.25, for the flat tip with no shaft --
an upper bound -- and the sphere everywhere else.
"""

from __future__ import annotations

FD_MICROWIRE_REFERENCE: dict[float, float] = {
    0.0: 0.1726,
    0.25: 0.1282,
    0.5: 0.1114,
    1.0: 0.0922,
    2.0: 0.0721,
    3.0: 0.0608,
    4.0: 0.0532,
    5.0: 0.0476,
    10.0: 0.0326,
    20.0: 0.0212,
}
"""Exposed shaft length in wire radii -> ``R * sigma * a`` for a flat-tipped wire."""

ZERO_LENGTH_UNCERTAINTY = 0.02
"""Relative uncertainty of the ``l = 0`` entry, from its slow re-entrant-corner convergence."""
